version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: vegan-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: veganCodex

volumes:
  mongodb_data: